# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59a8dc8f183e36ee6981c5969350e52660f74f458c0f68edc504451dd3b573d0da13b0f175a31f11b4788bd61633af4c828ace30eb5dbf28c515f9d56cab853c

test:
  secret_key_base: ebae7dd85deee3e1e9544cdc5e7908bbbb2ae615c7894a2bf9685e1a1b90409d6aced25e835136db93975752b75a8f53278777df77cd054420598e3cb9a7f929

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
